"""Embed builders for Phase 10 — AI Creative Factory."""

from __future__ import annotations

import discord

from .base import FOOTER_TEXT, make_embed


def _trunc(text: str, n: int) -> str:
    return text[:n] if text else "—"


def build_creative_pack_embeds(result: dict) -> list[discord.Embed]:
    """Return 5 embeds covering the full creative pack."""
    product   = result["product"]
    creative  = result["creative"]
    cid       = result["creative_id"]
    used_ai   = result.get("used_ai", False)
    platform  = product.get("platform") or result.get("platform", "universal")

    title_short = _trunc(product.get("title") or "", 55)
    short_url   = product.get("affiliate_short_url", "")

    embeds: list[discord.Embed] = []

    # ── Embed 1: Overview + Hooks + Facebook Caption ──────────────────────────
    e1 = make_embed(
        f"🎨 Creative Pack #{cid} — {title_short}",
        color_key="content",
    )
    e1.add_field(name="Platform",      value=platform.title(),                          inline=True)
    e1.add_field(name="Generated by",  value="✅ Claude AI" if used_ai else "📋 Template", inline=True)
    e1.add_field(name="Status",        value="`draft`",                                 inline=True)
    e1.add_field(name="Affiliate Link", value=short_url or "—",                         inline=False)

    hooks      = creative.get("hooks") or []
    hooks_text = "\n".join(f"`{i+1}.` {_trunc(h, 120)}" for i, h in enumerate(hooks[:3]))
    e1.add_field(name="🎣 Hook Options (3 variants)", value=hooks_text[:1024] or "—", inline=False)

    fb_cap = _trunc(creative.get("caption_facebook") or "", 1024)
    e1.add_field(name="📘 Facebook Caption", value=fb_cap or "—", inline=False)
    embeds.append(e1)

    # ── Embed 2: TikTok Caption + CTA + Hashtags ─────────────────────────────
    e2 = make_embed("📱 TikTok / Reels Caption", color_key="viral")
    e2.add_field(
        name="Caption",
        value=_trunc(creative.get("caption_tiktok") or "", 1024),
        inline=False,
    )
    e2.add_field(
        name="🎯 Call-to-Action",
        value=_trunc(creative.get("cta") or "", 512),
        inline=False,
    )
    e2.add_field(
        name="# Hashtags",
        value=_trunc(creative.get("hashtags") or "", 512),
        inline=False,
    )
    embeds.append(e2)

    # ── Embed 3: Image Prompts ─────────────────────────────────────────────────
    e3 = make_embed("🖼️ Image Prompts (for AI Image Generation)", color_key="niche")
    img = creative.get("image_prompt") or {}
    e3.add_field(name="1:1 — Facebook Feed",   value=_trunc(img.get("1_1") or "", 1024), inline=False)
    e3.add_field(name="4:5 — Facebook Ad",     value=_trunc(img.get("4_5") or "", 1024), inline=False)
    e3.add_field(name="9:16 — TikTok / Reels", value=_trunc(img.get("9_16") or "", 1024), inline=False)
    e3.set_footer(text="Paste these into Midjourney, DALL-E, or Ideogram")
    embeds.append(e3)

    # ── Embed 4: Video Storyboard ──────────────────────────────────────────────
    e4 = make_embed("🎬 Video Storyboard", color_key="trend")
    vp = creative.get("video_prompt") or {}

    v5 = vp.get("5s") or {}
    v5_text = (
        f"**Scene:** {_trunc(v5.get('scene',''), 200)}\n"
        f"**On-screen text:** {_trunc(v5.get('on_screen_text',''), 80)}\n"
        f"**Voice-over:** {_trunc(v5.get('voice_over',''), 150)}\n"
        f"**Music/SFX:** {_trunc(v5.get('music_sfx',''), 100)}"
    )
    e4.add_field(name="⚡ 5-Second Cut", value=v5_text[:1024], inline=False)

    v10 = vp.get("10s") or {}
    v10_scenes = "\n".join(
        f"**{s.get('sec','')}** {_trunc(s.get('scene',''), 80)} | `{_trunc(s.get('text',''), 50)}`"
        for s in (v10.get("scenes") or [])
    )
    v10_text = f"{v10_scenes}\n**Voice:** {_trunc(v10.get('voice_over',''), 200)}"
    e4.add_field(name="🎬 10-Second Cut", value=v10_text[:1024] or "—", inline=False)

    v15 = vp.get("15s") or {}
    v15_scenes = "\n".join(
        f"**{s.get('sec','')}** {_trunc(s.get('scene',''), 80)} | `{_trunc(s.get('text',''), 50)}`"
        for s in (v15.get("scenes") or [])
    )
    v15_text = f"{v15_scenes}\n**Voice:** {_trunc(v15.get('voice_over',''), 200)}"
    e4.add_field(name="🎥 15-Second Cut", value=v15_text[:1024] or "—", inline=False)
    embeds.append(e4)

    # ── Embed 5: Voice-Over Scripts + Creative Score ───────────────────────────
    e5 = make_embed("🎙️ Voice-Over Scripts & Creative Score", color_key="profit")
    vs = creative.get("voice_script") or {}
    e5.add_field(name="5s Script",  value=_trunc(vs.get("5s") or "", 512),  inline=False)
    e5.add_field(name="10s Script", value=_trunc(vs.get("10s") or "", 512), inline=False)
    e5.add_field(name="15s Script", value=_trunc(vs.get("15s") or "", 512), inline=False)

    score = creative.get("score") or {}
    if score:
        total = score.get("total", 0)
        bar   = "█" * int(total / 5) + "░" * (10 - int(total / 5))
        score_text = (
            f"🎣 Hook Strength:    `{score.get('hook_strength', 0)}/10`\n"
            f"💡 Clarity:         `{score.get('clarity', 0)}/10`\n"
            f"🛒 Purchase Intent: `{score.get('purchase_intent', 0)}/10`\n"
            f"📱 Platform Fit:    `{score.get('platform_fit', 0)}/10`\n"
            f"✅ Ad-Readiness:    `{score.get('ad_readiness', 0)}/10`\n"
            f"━━━━━━━━━━━━━━━━━━\n"
            f"**Total: `{total}/50`** `{bar}`\n"
            f"_{_trunc(score.get('verdict',''), 150)}_"
        )
        e5.add_field(name="📊 Creative Score", value=score_text[:1024], inline=False)

    e5.add_field(
        name="Approval Actions",
        value=f"✅ `/creative-approve {cid}` — publish  |  ❌ `/creative-reject {cid}` — discard",
        inline=False,
    )
    embeds.append(e5)

    return embeds


def build_creative_list_embeds(items: list[dict]) -> list[discord.Embed]:
    if not items:
        e = make_embed("📋 Creative Assets", color_key="info")
        e.description = "No creatives found."
        return [e]

    PAGE = 8
    pages: list[discord.Embed] = []
    for i in range(0, len(items), PAGE):
        chunk = items[i : i + PAGE]
        e = make_embed(
            f"📋 Creative Assets ({len(items)} total)",
            color_key="content",
        )
        lines = []
        for item in chunk:
            sc     = (item.get("score") or {}).get("total", "?")
            icon   = {"draft": "📝", "approved": "✅", "rejected": "❌"}.get(item["status"], "❓")
            date   = (item.get("created_at") or "")[:10]
            title  = _trunc(item.get("title") or "", 42)
            lines.append(
                f"`#{item['id']:>3}` {icon} **{title}**\n"
                f"       `{item['platform']}` | Score: `{sc}/50` | {date}"
            )
        e.description = "\n\n".join(lines)
        e.set_footer(text=f"{FOOTER_TEXT} • Page {len(pages)+1}")
        pages.append(e)

    return pages


def build_approve_embed(creative_id: int, status: str, title: str) -> discord.Embed:
    icon  = "✅" if status == "approved" else "❌"
    color = "success" if status == "approved" else "error"
    e = make_embed(f"{icon} Creative #{creative_id} {status.title()}", color_key=color)
    e.description = f"**{_trunc(title, 80)}**\nStatus updated to `{status}`."
    return e
